
-- Create services table
CREATE TABLE public.services (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  icon text NOT NULL DEFAULT '',
  path text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'planning',
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- Public can read services
CREATE POLICY "Public can read services"
ON public.services FOR SELECT
USING (true);

-- Admin CRUD
CREATE POLICY "Admins can insert services"
ON public.services FOR INSERT
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can update services"
ON public.services FOR UPDATE
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can delete services"
ON public.services FOR DELETE
USING (has_role(auth.uid(), 'admin'::app_role));

-- Trigger for updated_at
CREATE TRIGGER update_services_updated_at
BEFORE UPDATE ON public.services
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Create insights table
CREATE TABLE public.insights (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  excerpt text NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT 'trend',
  author text NOT NULL DEFAULT '',
  date text NOT NULL DEFAULT '',
  image text NOT NULL DEFAULT '',
  views integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.insights ENABLE ROW LEVEL SECURITY;

-- Public can read insights
CREATE POLICY "Public can read insights"
ON public.insights FOR SELECT
USING (true);

-- Admin CRUD
CREATE POLICY "Admins can insert insights"
ON public.insights FOR INSERT
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can update insights"
ON public.insights FOR UPDATE
USING (has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Admins can delete insights"
ON public.insights FOR DELETE
USING (has_role(auth.uid(), 'admin'::app_role));

-- Trigger for updated_at
CREATE TRIGGER update_insights_updated_at
BEFORE UPDATE ON public.insights
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Seed initial services data
INSERT INTO public.services (id, title, description, icon, path, category, display_order) VALUES
(1, '입지 분석', '유동인구, 경쟁 의료기관, 임대료 등을 고려한 최적 입지 선정', 'MapPin', '/services/location-analysis', 'planning', 1),
(2, '재무 컨설팅', '초기 투자비용 산정부터 손익분기점 예측까지 맞춤형 재무 계획', 'BarChart3', '/services/financial-consulting', 'planning', 2),
(3, '설계 및 인테리어', '진료과목별 최적 동선 설계 및 브랜드 아이덴티티를 반영한 인테리어', 'Building2', '/services/design-interior', 'implementation', 3),
(4, '인허가 대행', '복잡한 행정 절차를 원스톱으로 처리하는 인허가 대행 서비스', 'FileCheck', '/services/licensing', 'implementation', 4),
(5, '인력 채용', '전문 의료인력 채용 및 교육 프로그램 지원', 'Users', '/services/recruitment', 'operation', 5),
(6, '마케팅 전략', '개원 초기 인지도 확보부터 지속 가능한 환자 유치 전략 수립', 'Briefcase', '/services/marketing-strategy', 'operation', 6),
(7, '의료기기 구입 및 설치', '최적의 의료장비 선정부터 설치, A/S까지 원스톱 제공', 'Package', '/services/medical-equipment', 'equipment', 7),
(8, '수납 및 의료폐기물 처리', '의료폐기물 처리 계약부터 효율적인 수납 시스템 구축까지', 'Trash2', '/services/waste-management', 'equipment', 8);

-- Seed initial insights data
INSERT INTO public.insights (id, title, excerpt, content, category, author, date, image, views) VALUES
(1, '2023년 의료기관 개원 트렌드 분석', '최근 의료기관 개원 트렌드와 성공적인 개원을 위한 핵심 요소를 분석합니다.', '최근 의료기관 개원 트렌드는 대형화, 전문화, 디지털화로 요약할 수 있습니다. 특히 비대면 진료와 디지털 헬스케어 솔루션 도입이 큰 트렌드로 자리잡고 있습니다.', 'trend', '김전문', '2023-03-15', 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=2070&auto=format&fit=crop', 1240),
(2, '성공적인 의원 마케팅 전략 5가지', '경쟁이 치열한 의료 시장에서 효과적인 마케팅 전략으로 차별화를 이루는 방법을 소개합니다.', '성공적인 의원 마케팅을 위해서는 1) 타겟 환자군 명확화, 2) 디지털 마케팅 활용, 3) 환자 경험 최적화, 4) 지역 커뮤니티 참여, 5) 전문성 강조가 필요합니다.', 'marketing', '박마케팅', '2023-04-02', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=2070&auto=format&fit=crop', 980),
(3, '의료기관 인허가 절차 간소화 가이드', '복잡한 의료기관 인허가 절차를 효율적으로 진행하기 위한 단계별 가이드를 제공합니다.', '의료기관 인허가 절차는 크게 1) 사전 준비, 2) 건축 허가, 3) 의료기관 개설 신고, 4) 사업자 등록, 5) 기타 인허가로 나뉩니다. 각 단계별 필요 서류와 주의사항을 안내합니다.', 'licensing', '이인허가', '2023-02-20', 'https://images.unsplash.com/photo-1581360742512-021d5b2157d8?q=80&w=2069&auto=format&fit=crop', 1560),
(4, '의료기관 재무 관리의 핵심 지표', '의료기관의 건전한 재무 상태를 유지하기 위한 핵심 재무 지표와 관리 방법을 소개합니다.', '의료기관의 재무 건전성을 평가하기 위한 핵심 지표로는 1) 수익성 지표, 2) 유동성 지표, 3) 활동성 지표, 4) 안정성 지표가 있으며, 각 지표별 목표 수치와 개선 방법을 제시합니다.', 'finance', '최재무', '2023-03-10', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2015&auto=format&fit=crop', 1120),
(5, '의료진 채용 및 관리 베스트 프랙티스', '효과적인 의료진 채용 전략과 장기적 인력 관리 방안에 대한 가이드를 제공합니다.', '의료기관의 성공은 우수한 인력 확보와 유지에 달려있습니다. 채용 과정의 투명성, 지속적인 교육 기회 제공, 공정한 평가 시스템, 적절한 보상체계 구축이 핵심입니다.', 'recruitment', '정인사', '2023-04-05', 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?q=80&w=2070&auto=format&fit=crop', 890),
(6, '최신 의료장비 도입 가이드 - ROI를 높이는 선택', '의료기관에 새로운 장비를 도입할 때 고려해야 할 요소와 투자 대비 수익을 최대화하는 방법을 안내합니다.', '의료장비 도입 시 1) 수요 분석, 2) 비용 대비 효과, 3) 유지보수 계획, 4) 사용자 교육, 5) 보험 수가 검토가 필수적입니다. 장비별 특성과 진료과목에 따른 맞춤형 선택 방법을 제시합니다.', 'equipment', '강장비', '2023-03-28', 'https://images.unsplash.com/photo-1516549655169-df83a0774514?q=80&w=2070&auto=format&fit=crop', 760);
